language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
  - "tip"
before_install:
  - go get -u -d github.com/magefile/mage
  - cd $GOPATH/src/github.com/magefile/mage && go run bootstrap.go
install:
  - mage install
script:
  - mage all
